tune_config: 
  mode: "min"
  metric: "validation_loss"
  num_samples: 2

scheduler: 
  "ASHAScheduler"

scheduler_config:
  max_t: 100
  grace_period: 1
  reduction_factor: 2

search_space: 
  learning_rate:
    lower: 0.0001
    upper: 0.1
  epochs:
    lower: 5
    upper: 50
    integer: true
  loss_function:
    choices: ["PoissonNLLLoss"]
  optimizer:
    choices: ["Adam"]



