tune_config: 
  mode: "min"
  metric: "validation_loss"
  num_samples: 2

scheduler: 
  "ASHAScheduler"

scheduler_config:
  max_t: 100
  grace_period: 1
  reduction_factor: 2

search_space: 
  learning_rate:
    lower: 0.0001
    upper: 0.1
  epochs:
    lower: 5
    upper: 50
    integer: true
  loss_function:
    choices: ["PoissonNLLLoss"]
  optimizer:
    choices: ["Adam"]

  batch_size:
    space : [16, 32, 64, 128, 256, 512, 1024]
    mode: choice

  learning_rate:
    space: [2,10]
    mode: range
