tune_config: 
  mode: "min"
  metric: "validation_loss"
  num_samples: 1

scheduler: 
  "ASHAScheduler"

scheduler_config:
  max_t: 1
  grace_period: 1
  reduction_factor: 2

search_space: 
  learning_rate:
    lower: 0.0001
    upper: 0.1
  epochs:
    lower: 5
    upper: 20
    integer: true
  loss_function:
    choices: ["PoissonNLLLoss", "MSELoss"]
  optimizer:
    choices: ["Adam", "SGD"]



